# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Starter pipeline
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Professional Subscription(e394c692-7ebe-4f4e-9241-b64f461672fc)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks create --resource-group kaushik --name aks-deployment-test --node-count 5 --node-vm-size Standard_DS3_v2 --enable-addons monitoring --generate-ssh-key'
    useGlobalConfig: true
    failOnStandardError: true

- task: AzureCLI@2
  inputs:
        azureSubscription: 'Visual Studio Professional Subscription(e394c692-7ebe-4f4e-9241-b64f461672fc)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az aks install-cli'
        useGlobalConfig: true
        failOnStandardError: true

- task: AzureCLI@2
  inputs:
        azureSubscription: 'Visual Studio Professional Subscription(e394c692-7ebe-4f4e-9241-b64f461672fc)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az aks get-credentials --resource-group kaushik --name aks-deployment-test'
        useGlobalConfig: true
        failOnStandardError: true